version: "3"

services:

  mysql:
    image: mysql:9.2
    command: --max-allowed-packet=64MB
    #restart: always
    volumes:
      - ${MYSQL_DATA_VOLUME_PATH}:/var/lib/mysql:Z
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3306:3306"

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    #restart: always
    volumes:
      - ${MSSQL_DATA_VOLUME_PATH}:/var/opt/mssql
    environment:
      - ACCEPT_EULA=${MSSQL_ACCEPT_EULA}
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
 


